name: Compute coverage

on:
  push:
    branches:
      - master
    paths: 
      - "src/main/**.java"
      - "src/test/**.java"
 #     - ".github/workflows/**"
      - "**.properties"
      - "**.xml"

jobs:
  compute-coverage:
    name: Compute coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          architecture: x64
      - name: Build and test
        run: mvn clean test -DskipTests=false -Dproject.test.testSuite=AllTestsSuite -P run-coveralls jacoco:report coveralls:report -DrepoToken=${{ secrets.coveralls_repo_token }}

